# Generated by Django 5.0.6 on 2024-11-28 17:44

import adl_ftp_plugin.utils
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('ftp_path', models.CharField(max_length=255, verbose_name='FTP Path')),
                ('file_pattern', models.CharField(max_length=255, verbose_name='File Pattern')),
            ],
            options={
                'verbose_name': 'FTP Station Link',
                'verbose_name_plural': 'FTP Station Links',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='NetworkFTP',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('decoder', models.CharField(choices=adl_ftp_plugin.utils.get_ftp_decoder_choices, max_length=255, verbose_name='Decoder')),
                ('extract_date_from_filename', models.BooleanField(default=False, verbose_name='Extract Observation Date from Filename')),
            ],
            options={
                'verbose_name': 'Network FTP',
                'verbose_name_plural': 'Network FTPs',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='FTPVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('file_variable_name', models.CharField(max_length=255, verbose_name='File Variable Name')),
                ('file_variable_units', models.CharField(max_length=255, verbose_name='File Variable Units')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Variable')),
                ('network_ftp', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_ftp_plugin.networkftp')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
