# Generated by Django 5.0.6 on 2025-01-09 11:13

import adl_ftp_plugin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTPStationDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file', models.FileField(upload_to=adl_ftp_plugin.models.get_ftp_data_file_upload_path, verbose_name='File')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
            ],
            options={
                'verbose_name': 'FTP Station Data File',
                'verbose_name_plural': 'FTP Station Data Files',
            },
        ),
    ]
