# Generated by Django 5.0.6 on 2024-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkftp',
            name='extract_date_from_filename',
        ),
        migrations.AddField(
            model_name='ftpstationlink',
            name='extract_date_from_filename',
            field=models.BooleanField(default=False, verbose_name='Extract Observation Date from Filename'),
        ),
    ]
