# Generated by Django 5.0.6 on 2025-01-09 11:13

import adl_ftp_plugin.utils
import adl_ftp_plugin.validators
import django.db.models.deletion
import modelcluster.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adl_ftp_plugin', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('ftp_path', models.CharField(help_text='Path to the directory containing the data files', max_length=255, verbose_name='FTP Path')),
                ('file_pattern', models.CharField(max_length=255, verbose_name='File Pattern')),
                ('dir_structured_by_date', models.BooleanField(default=False, help_text='Check if the files are structured by a combination of year, month, day or hour in the FTP path. Folders structure expected to be in the format [YYYY]/[MM]/[DD]/[HH]', verbose_name='Directory Structured by Date ?')),
                ('date_granularity', models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day'), ('hour', 'Hour')], help_text='How far down the date hierarchy is the file located ? This will be used to construct the final name of the folder in the FTP path', max_length=255, null=True, verbose_name='Date Granularity')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Station Timezone')),
                ('start_date', models.DateTimeField(blank=True, help_text='Select a past date to include the historical data. Leave blank for collecting realtime data only', null=True, validators=[adl_ftp_plugin.validators.validate_start_date], verbose_name='Start Date for Data Collection')),
                ('skip_already_downloaded_files', models.BooleanField(default=True, help_text='Do not download files that have already been downloaded', verbose_name='Skip downloading already downloaded files')),
                ('skip_already_processed_files', models.BooleanField(default=True, help_text='Do not process files that have already been processed', verbose_name='Skip processing already processed files')),
            ],
            options={
                'verbose_name': 'FTP Station Link',
                'verbose_name_plural': 'FTP Station Links',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='NetworkFTP',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('decoder', models.CharField(choices=adl_ftp_plugin.utils.get_ftp_decoder_choices, max_length=255, verbose_name='Decoder')),
            ],
            options={
                'verbose_name': 'Network FTP',
                'verbose_name_plural': 'Network FTPs',
            },
            bases=('core.networkconnection',),
        ),
        migrations.AddField(
            model_name='ftpstationdatafile',
            name='station_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='adl_ftp_plugin.ftpstationlink'),
        ),
        migrations.CreateModel(
            name='FTPVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('file_variable_name', models.CharField(max_length=255, verbose_name='File Variable Name')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('file_variable_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='File Variable Unit')),
                ('network_ftp', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_ftp_plugin.networkftp')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ftpstationdatafile',
            name='variable_mappings',
            field=models.ManyToManyField(to='adl_ftp_plugin.ftpvariablemapping', verbose_name='Variable Mappings'),
        ),
    ]
