# Generated by Django 5.1.4 on 2025-02-28 09:04

import adl_ftp_plugin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpstationlink',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date for data pulling. Select a past date to include the historical data. Leave blank for collecting realtime data only', null=True, validators=[adl_ftp_plugin.validators.validate_start_date], verbose_name='Start Date'),
        ),
    ]
