# Generated by Django 5.0.6 on 2024-11-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0002_remove_networkftp_extract_date_from_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpstationlink',
            name='date_granularity',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day')], max_length=255, null=True, verbose_name='Date Granularity'),
        ),
        migrations.AddField(
            model_name='ftpstationlink',
            name='dir_structured_by_date',
            field=models.BooleanField(default=False, verbose_name='Directory Structured by Date'),
        ),
    ]
