# Generated by Django 5.1.4 on 2025-04-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0003_alter_ftpstationlink_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpstationlink',
            name='month_dir_format',
            field=models.CharField(blank=True, choices=[('m', "Month, 2 digits with leading zeros. '01' to '12'"), ('n', "Month without leading zeros. '1' to '12'"), ('M', "Month, textual, 3 letters. 'Jan'"), ('b', "Month, textual, 3 letters, lowercase. 'jan'"), ('F', "Month, textual, full. 'January'"), ('f', "Month, textual, full, lowercase. 'january'")], default='m', max_length=255, null=True, verbose_name='Month directory Format'),
        ),
    ]
