# Generated by Django 5.0.6 on 2024-11-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0004_ftpstationlink_date_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpstationlink',
            name='date_pattern',
            field=models.CharField(blank=True, choices=[('YYYYMMDDHHMM', '*_YYYYMMDDHHMM.*'), ('YYYYMMDDHHMMSS', '*_YYYYMMDDHHMMSS.*')], max_length=255, null=True, verbose_name='Filename Date Pattern'),
        ),
    ]
