# Generated by Django 5.1.9 on 2025-07-08 13:14

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0005_ftpstationlinkvariablemapping'),
        ('core', '0017_dataparameter_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPUpload',
            fields=[
                ('dispatchchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.dispatchchannel')),
                ('host', models.CharField(max_length=255, verbose_name='FTP Host')),
                ('port', models.CharField(max_length=255, verbose_name='FTP Port')),
                ('user', models.CharField(max_length=255, verbose_name='FTP User')),
                ('password', models.CharField(max_length=255, verbose_name='FTP Password')),
                ('directory', models.CharField(help_text='Directory on the FTP server to upload files to', max_length=255, verbose_name='FTP Directory')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Timezone to use for date/time')),
            ],
            options={
                'verbose_name': 'FTP Upload',
                'verbose_name_plural': 'FTP Uploads',
            },
            bases=('core.dispatchchannel',),
        ),
    ]
