# Generated by Django 5.0.6 on 2024-11-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0005_alter_ftpstationlink_date_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftpstationlink',
            name='date_pattern',
        ),
        migrations.RemoveField(
            model_name='ftpstationlink',
            name='extract_date_from_filename',
        ),
    ]
