# Generated by Django 5.0.6 on 2024-11-28 21:40

import adl_ftp_plugin.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0006_remove_ftpstationlink_date_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPStationDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file', models.FileField(upload_to=adl_ftp_plugin.models.get_ftp_data_file_upload_path, verbose_name='File')),
                ('station_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='adl_ftp_plugin.ftpstationlink')),
            ],
            options={
                'verbose_name': 'FTP Station Data File',
                'verbose_name_plural': 'FTP Station Data Files',
            },
        ),
    ]
