# Generated by Django 5.1.9 on 2025-07-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0006_ftpupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpupload',
            name='write_mode',
            field=models.CharField(choices=[('append', 'Append record to single daily file'), ('new_file', 'Create a new file for each record')], default='append', max_length=20, verbose_name='FTP Write Mode'),
        ),
    ]
