# Generated by Django 5.1.9 on 2025-08-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0007_ftpupload_write_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftpstationlink',
            name='timezone',
        ),
    ]
