# Generated by Django 5.1.9 on 2025-09-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0008_remove_ftpstationlink_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkftp',
            name='passive_mode',
            field=models.BooleanField(default=True, verbose_name='Use FTP Passive mode'),
        ),
    ]
