# Generated by Django 5.0.6 on 2024-11-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0008_ftpstationdatafile_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpstationlink',
            name='skip_already_processed_files',
            field=models.BooleanField(default=True, verbose_name='Skip Already Processed Files'),
        ),
    ]
