# Generated by Django 5.1.9 on 2025-09-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0009_networkftp_passive_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkftp',
            name='secure',
            field=models.BooleanField(default=False, verbose_name='Secure'),
        ),
    ]
