# Generated by Django 5.0.6 on 2024-11-29 07:02

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0009_ftpstationlink_skip_already_processed_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpstationlink',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Station Timezone'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='date_granularity',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day'), ('hour', 'Hour')], max_length=255, null=True, verbose_name='Date Granularity'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='skip_already_processed_files',
            field=models.BooleanField(default=True, verbose_name='Skip already downloaded and processed Files'),
        ),
    ]
