# Generated by Django 5.1.9 on 2025-09-25 18:55

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0010_networkftp_secure'),
        ('core', '0031_remove_dispatchchannel_network_connection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMetFTPUpload',
            fields=[
                ('dispatchchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.dispatchchannel')),
                ('host', models.CharField(max_length=255, verbose_name='FTP Host')),
                ('port', models.CharField(max_length=255, verbose_name='FTP Port')),
                ('user', models.CharField(max_length=255, verbose_name='FTP User')),
                ('password', models.CharField(max_length=255, verbose_name='FTP Password')),
                ('directory', models.CharField(help_text='Directory on the FTP server to upload files to', max_length=255, verbose_name='FTP Directory')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Timezone to use for date/time')),
                ('write_mode', models.CharField(choices=[('append', 'Append record to single daily file'), ('new_file', 'Create a new file for each record')], default='append', max_length=20, verbose_name='FTP Write Mode')),
            ],
            options={
                'verbose_name': 'SmartMet FTP Upload',
            },
            bases=('core.dispatchchannel',),
        ),
        migrations.AlterModelOptions(
            name='ftpupload',
            options={'verbose_name': 'Standard FTP Upload', 'verbose_name_plural': 'Standard FTP Uploads'},
        ),
    ]
