# Generated by Django 5.0.6 on 2024-11-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0010_ftpstationlink_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpstationlink',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
