# Generated by Django 5.0.6 on 2024-11-29 08:43

import adl_ftp_plugin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0011_ftpstationlink_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpstationlink',
            name='skip_already_downloaded_files',
            field=models.BooleanField(default=True, help_text='Do not download files that have already been downloaded', verbose_name='Skip downloading already downloaded files'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='skip_already_processed_files',
            field=models.BooleanField(default=True, help_text='Do not process files that have already been processed', verbose_name='Skip processing already processed files'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date for data collection', null=True, validators=[adl_ftp_plugin.validators.validate_start_date], verbose_name='Start Date'),
        ),
    ]
