# Generated by Django 5.1.9 on 2025-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0011_smartmetftpupload_alter_ftpupload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartmetftpupload',
            options={},
        ),
        migrations.AddField(
            model_name='ftpupload',
            name='passive',
            field=models.BooleanField(default=False, verbose_name='Use FTP Passive Mode'),
        ),
        migrations.AddField(
            model_name='smartmetftpupload',
            name='passive',
            field=models.BooleanField(default=False, verbose_name='Use FTP Passive Mode'),
        ),
    ]
