# Generated by Django 5.1.9 on 2025-09-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0012_alter_smartmetftpupload_options_ftpupload_passive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartmetftpupload',
            options={'verbose_name': 'SmartMet FTP Upload', 'verbose_name_plural': 'SmartMet FTP Uploads'},
        ),
    ]
