# Generated by Django 5.0.6 on 2024-11-29 12:51

import adl_ftp_plugin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0012_ftpstationlink_skip_already_downloaded_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpstationlink',
            name='date_granularity',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day'), ('hour', 'Hour')], help_text='How far down the date hierarchy is the file located ? This will be used to construct the final name of the folder in the FTP path', max_length=255, null=True, verbose_name='Date Granularity'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='dir_structured_by_date',
            field=models.BooleanField(default=False, help_text='Check if the files are structured by a combination of year, month, day or hour in the FTP path. Folders structure expected to be in the format [YYYY]/[MM]/[DD]/[HH]', verbose_name='Directory Structured by Date ?'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='ftp_path',
            field=models.CharField(help_text='Path to the directory containing the data files', max_length=255, verbose_name='FTP Path'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Select a past date to include the historical data. Leave blank for collecting realtime data only', null=True, validators=[adl_ftp_plugin.validators.validate_start_date], verbose_name='Start Date for Data Collection'),
        ),
    ]
