# Generated by Django 5.1.9 on 2025-09-26 03:31

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0013_alter_smartmetftpupload_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpupload',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone to use for file dates. UTC highly recommended', verbose_name='Timezone for output dates'),
        ),
        migrations.AlterField(
            model_name='smartmetftpupload',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone to use for file dates. UTC highly recommended', verbose_name='Timezone for output dates'),
        ),
    ]
