# Generated by Django 5.1.9 on 2025-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0014_alter_ftpupload_timezone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ftpstationdatafile',
            options={'verbose_name': 'Remote Station Data File', 'verbose_name_plural': 'Remote Station Data Files'},
        ),
        migrations.AlterModelOptions(
            name='ftpstationlink',
            options={'verbose_name': 'FTP/SFTP Station Link', 'verbose_name_plural': 'FTP/SFTP Station Links'},
        ),
        migrations.AlterModelOptions(
            name='ftpupload',
            options={'verbose_name': 'Standard FTP/SFTP Upload', 'verbose_name_plural': 'Standard FTP/SFTP Uploads'},
        ),
        migrations.AlterModelOptions(
            name='networkftp',
            options={'verbose_name': 'Network FTP/SFTP', 'verbose_name_plural': 'Network FTP/SFTPs'},
        ),
        migrations.AlterModelOptions(
            name='smartmetftpupload',
            options={'verbose_name': 'SmartMet FTP/SFTP Upload', 'verbose_name_plural': 'SmartMet FTP/SFTP Uploads'},
        ),
        migrations.AddField(
            model_name='ftpupload',
            name='connection_type',
            field=models.CharField(choices=[('ftp', 'FTP'), ('ftps', 'FTPS (FTP over TLS)'), ('sftp', 'SFTP (SSH File Transfer)')], default='ftp', max_length=10, verbose_name='Connection Type'),
        ),
        migrations.AddField(
            model_name='ftpupload',
            name='host_key_policy',
            field=models.CharField(choices=[('auto', 'Auto-accept (less secure)'), ('warn', 'Warn but connect'), ('reject', 'Reject unknown hosts (most secure)')], default='auto', max_length=10, verbose_name='Host Key Policy'),
        ),
        migrations.AddField(
            model_name='ftpupload',
            name='private_key_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='Private Key File'),
        ),
        migrations.AddField(
            model_name='ftpupload',
            name='secure',
            field=models.BooleanField(default=False, verbose_name='Secure (FTPS)'),
        ),
        migrations.AddField(
            model_name='networkftp',
            name='connection_type',
            field=models.CharField(choices=[('ftp', 'FTP'), ('ftps', 'FTPS (FTP over TLS)'), ('sftp', 'SFTP (SSH File Transfer)')], default='ftp', help_text='Protocol to use for file transfer', max_length=10, verbose_name='Connection Type'),
        ),
        migrations.AddField(
            model_name='networkftp',
            name='host_key_policy',
            field=models.CharField(choices=[('auto', 'Auto-accept (less secure)'), ('warn', 'Warn but connect'), ('reject', 'Reject unknown hosts (most secure)')], default='auto', help_text='How to handle unknown SSH host keys (SFTP only)', max_length=10, verbose_name='Host Key Policy'),
        ),
        migrations.AddField(
            model_name='networkftp',
            name='private_key_file',
            field=models.CharField(blank=True, help_text='Path to SSH private key file (for SFTP). Optional if using password', max_length=500, verbose_name='Private Key File Path'),
        ),
        migrations.AddField(
            model_name='networkftp',
            name='timeout',
            field=models.IntegerField(default=20, verbose_name='Connection Timeout (seconds)'),
        ),
        migrations.AddField(
            model_name='smartmetftpupload',
            name='connection_type',
            field=models.CharField(choices=[('ftp', 'FTP'), ('ftps', 'FTPS (FTP over TLS)'), ('sftp', 'SFTP (SSH File Transfer)')], default='ftp', max_length=10, verbose_name='Connection Type'),
        ),
        migrations.AddField(
            model_name='smartmetftpupload',
            name='host_key_policy',
            field=models.CharField(choices=[('auto', 'Auto-accept (less secure)'), ('warn', 'Warn but connect'), ('reject', 'Reject unknown hosts (most secure)')], default='auto', max_length=10, verbose_name='Host Key Policy'),
        ),
        migrations.AddField(
            model_name='smartmetftpupload',
            name='private_key_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='Private Key File'),
        ),
        migrations.AddField(
            model_name='smartmetftpupload',
            name='secure',
            field=models.BooleanField(default=False, verbose_name='Secure (FTPS)'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='date_granularity',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day'), ('hour', 'Hour')], help_text='How far down the date hierarchy is the file located ? This will be used to construct the final name of the folder in the remote path', max_length=255, null=True, verbose_name='Date Granularity'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='dir_structured_by_date',
            field=models.BooleanField(default=False, help_text='Check if the files are structured by a combination of year, month, day or hour in the remote path. Folders structure expected to be in the format [YYYY]/[MM]/[DD]/[HH]', verbose_name='Directory Structured by Date ?'),
        ),
        migrations.AlterField(
            model_name='ftpstationlink',
            name='ftp_path',
            field=models.CharField(help_text='Path to the directory containing the data files', max_length=255, verbose_name='Remote Path'),
        ),
        migrations.AlterField(
            model_name='ftpupload',
            name='directory',
            field=models.CharField(help_text='Directory on the server to upload files to', max_length=255, verbose_name='Remote Directory'),
        ),
        migrations.AlterField(
            model_name='ftpupload',
            name='host',
            field=models.CharField(max_length=255, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='ftpupload',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='ftpupload',
            name='port',
            field=models.CharField(blank=True, help_text='Leave blank for default (21 for FTP/FTPS, 22 for SFTP)', max_length=255, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='ftpupload',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='ftpupload',
            name='write_mode',
            field=models.CharField(choices=[('append', 'Append record to single daily file'), ('new_file', 'Create a new file for each record')], default='append', max_length=20, verbose_name='Write Mode'),
        ),
        migrations.AlterField(
            model_name='networkftp',
            name='passive_mode',
            field=models.BooleanField(default=True, help_text='Only applies to FTP/FTPS connections', verbose_name='Use FTP Passive mode'),
        ),
        migrations.AlterField(
            model_name='networkftp',
            name='password',
            field=models.CharField(blank=True, help_text='Required for FTP/FTPS, optional for SFTP with key auth', max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='networkftp',
            name='port',
            field=models.IntegerField(blank=True, help_text='Leave blank for default ports (21 for FTP/FTPS, 22 for SFTP)', null=True, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='networkftp',
            name='secure',
            field=models.BooleanField(default=False, help_text='Use TLS encryption for FTP. Only applies to FTP connections', verbose_name='Secure (FTPS)'),
        ),
        migrations.AlterField(
            model_name='smartmetftpupload',
            name='directory',
            field=models.CharField(help_text='Directory on the server to upload files to', max_length=255, verbose_name='Remote Directory'),
        ),
        migrations.AlterField(
            model_name='smartmetftpupload',
            name='host',
            field=models.CharField(max_length=255, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='smartmetftpupload',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='smartmetftpupload',
            name='port',
            field=models.CharField(blank=True, help_text='Leave blank for default (21 for FTP/FTPS, 22 for SFTP)', max_length=255, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='smartmetftpupload',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='smartmetftpupload',
            name='write_mode',
            field=models.CharField(choices=[('append', 'Append record to single daily file'), ('new_file', 'Create a new file for each record')], default='append', max_length=20, verbose_name='Write Mode'),
        ),
    ]
