# Generated by Django 5.1.9 on 2025-09-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0015_alter_ftpstationdatafile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpupload',
            name='allow_agent',
            field=models.BooleanField(default=False, verbose_name='Allow SSH Agent'),
        ),
        migrations.AddField(
            model_name='ftpupload',
            name='look_for_keys',
            field=models.BooleanField(default=False, verbose_name='Look for SSH Keys'),
        ),
        migrations.AddField(
            model_name='networkftp',
            name='allow_agent',
            field=models.BooleanField(default=False, help_text='Use SSH agent for authentication if available. SFTP only', verbose_name='Allow SSH Agent'),
        ),
        migrations.AddField(
            model_name='networkftp',
            name='look_for_keys',
            field=models.BooleanField(default=False, help_text='Automatically search for SSH keys in default locations (~/.ssh/). SFTP only', verbose_name='Look for SSH Keys'),
        ),
        migrations.AddField(
            model_name='smartmetftpupload',
            name='allow_agent',
            field=models.BooleanField(default=False, verbose_name='Allow SSH Agent'),
        ),
        migrations.AddField(
            model_name='smartmetftpupload',
            name='look_for_keys',
            field=models.BooleanField(default=False, verbose_name='Look for SSH Keys'),
        ),
    ]
