# Generated by Django 5.1.9 on 2025-09-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0016_ftpupload_allow_agent_ftpupload_look_for_keys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpupload',
            name='passive',
            field=models.BooleanField(default=True, verbose_name='Use FTP Passive Mode'),
        ),
        migrations.AlterField(
            model_name='smartmetftpupload',
            name='passive',
            field=models.BooleanField(default=True, verbose_name='Use FTP Passive Mode'),
        ),
    ]
