# Generated by Django 5.1.9 on 2025-10-02 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0017_alter_ftpupload_passive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardCSVConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='A descriptive name for this CSV configuration', max_length=255, verbose_name='Configuration Name')),
                ('datetime_mode', models.CharField(choices=[('single', 'Single datetime column'), ('separate', 'Separate date and time columns')], default='single', help_text='Whether datetime is in one column or split into date and time columns', max_length=20, verbose_name='Datetime Mode')),
                ('datetime_column', models.CharField(blank=True, help_text='Name of the column containing datetime (for single column mode)', max_length=255, verbose_name='Datetime Column Name')),
                ('datetime_format', models.CharField(blank=True, choices=[('%Y-%m-%d %H:%M:%S', '2025-01-15 14:30:45 (ISO 8601)'), ('%Y-%m-%d %H:%M:%S.%f', '2025-01-15 14:30:45.123456 (with microseconds)'), ('%Y-%m-%dT%H:%M:%S', '2025-01-15T14:30:45 (ISO 8601 with T)'), ('%Y-%m-%dT%H:%M:%SZ', '2025-01-15T14:30:45Z (ISO 8601 UTC)'), ('%Y-%m-%d %H:%M', '2025-01-15 14:30 (no seconds)'), ('%d/%m/%Y %H:%M:%S', '15/01/2025 14:30:45 (European)'), ('%d/%m/%Y %H:%M', '15/01/2025 14:30 (European, no seconds)'), ('%m/%d/%Y %H:%M:%S', '01/15/2025 14:30:45 (US)'), ('%m/%d/%Y %H:%M', '01/15/2025 14:30 (US, no seconds)'), ('%d-%m-%Y %H:%M:%S', '15-01-2025 14:30:45 (European with dash)'), ('%m-%d-%Y %H:%M:%S', '01-15-2025 14:30:45 (US with dash)'), ('%Y%m%d%H%M%S', '20250115143045 (compact)'), ('%Y%m%d %H%M%S', '20250115 143045 (compact with space)'), ('%d.%m.%Y %H:%M:%S', '15.01.2025 14:30:45 (German)'), ('%d.%m.%Y %H:%M', '15.01.2025 14:30 (German, no seconds)'), ('%Y/%m/%d %H:%M:%S', '2025/01/15 14:30:45 (with slashes)'), ('%d %b %Y %H:%M:%S', '15 Jan 2025 14:30:45 (abbreviated month)'), ('%d %B %Y %H:%M:%S', '15 January 2025 14:30:45 (full month)'), ('%Y-%m-%d %I:%M:%S %p', '2025-01-15 02:30:45 PM (12-hour)'), ('%m/%d/%Y %I:%M:%S %p', '01/15/2025 02:30:45 PM (US 12-hour)'), ('%d/%m/%Y %I:%M:%S %p', '15/01/2025 02:30:45 PM (European 12-hour)'), ('%a, %d %b %Y %H:%M:%S', 'Wed, 15 Jan 2025 14:30:45 (RFC 2822)')], default='%Y-%m-%d %H:%M:%S', help_text='Select the format that matches your datetime column', max_length=255, verbose_name='Datetime Format')),
                ('date_column', models.CharField(blank=True, help_text='Name of the column containing date (for separate columns mode)', max_length=255, verbose_name='Date Column Name')),
                ('date_format', models.CharField(blank=True, choices=[('%Y-%m-%d', '2025-01-15 (ISO 8601)'), ('%d/%m/%Y', '15/01/2025 (European)'), ('%m/%d/%Y', '01/15/2025 (US)'), ('%d-%m-%Y', '15-01-2025 (European with dash)'), ('%m-%d-%Y', '01-15-2025 (US with dash)'), ('%Y/%m/%d', '2025/01/15 (with slashes)'), ('%d.%m.%Y', '15.01.2025 (German)'), ('%Y%m%d', '20250115 (compact)'), ('%d %b %Y', '15 Jan 2025 (abbreviated month)'), ('%d %B %Y', '15 January 2025 (full month)'), ('%b %d, %Y', 'Jan 15, 2025 (US style)'), ('%B %d, %Y', 'January 15, 2025 (US style, full month)'), ('%d-%b-%Y', '15-Jan-2025 (dash with abbreviated month)'), ('%Y.%m.%d', '2025.01.15 (dot separator)'), ('%d/%m/%y', '15/01/25 (2-digit year, European)'), ('%m/%d/%y', '01/15/25 (2-digit year, US)'), ('%y-%m-%d', '25-01-15 (2-digit year first)'), ('%y%m%d', '250115 (compact 2-digit year)')], default='%Y-%m-%d', help_text='Select the format that matches your date column', max_length=255, verbose_name='Date Format')),
                ('time_column', models.CharField(blank=True, help_text='Name of the column containing time (for separate columns mode)', max_length=255, verbose_name='Time Column Name')),
                ('time_format', models.CharField(blank=True, choices=[('%H:%M:%S', '14:30:45 (24-hour with seconds)'), ('%H:%M', '14:30 (24-hour without seconds)'), ('%H:%M:%S.%f', '14:30:45.123456 (with microseconds)'), ('%I:%M:%S %p', '02:30:45 PM (12-hour with seconds)'), ('%I:%M %p', '02:30 PM (12-hour without seconds)'), ('%H%M%S', '143045 (compact 24-hour)'), ('%H%M', '1430 (compact 24-hour, no seconds)'), ('%I:%M:%S%p', '02:30:45PM (12-hour, no space)'), ('%I:%M%p', '02:30PM (12-hour, no seconds, no space)'), ('%H.%M.%S', '14.30.45 (dot separator)'), ('%H.%M', '14.30 (dot separator, no seconds)')], default='%H:%M:%S', help_text='Select the format that matches your time column', max_length=255, verbose_name='Time Format')),
                ('delimiter', models.CharField(default=',', help_text='Character used to separate values (default: comma)', max_length=5, verbose_name='CSV Delimiter')),
                ('skip_rows', models.IntegerField(default=0, help_text='Number of rows to skip before the header row', verbose_name='Skip Rows')),
            ],
            options={
                'verbose_name': 'Standard CSV Configuration',
                'verbose_name_plural': 'Standard CSV Configurations',
            },
        ),
        migrations.AddField(
            model_name='networkftp',
            name='csv_config',
            field=models.ForeignKey(blank=True, help_text="Configuration for standard CSV files (only used with 'standard_csv' decoder)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='adl_ftp_plugin.standardcsvconfig', verbose_name='CSV Configuration'),
        ),
    ]
