# Generated by Django 5.1.9 on 2025-10-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0018_standardcsvconfig_networkftp_csv_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardcsvconfig',
            options={'verbose_name': 'CSV Decoder Configuration', 'verbose_name_plural': 'CSV Decoder Configurations'},
        ),
        migrations.AlterField(
            model_name='networkftp',
            name='csv_config',
            field=models.ForeignKey(blank=True, help_text='Configuration for standard CSV files', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adl_ftp_plugin.standardcsvconfig', verbose_name='CSV Configuration'),
        ),
        migrations.AlterField(
            model_name='standardcsvconfig',
            name='date_format',
            field=models.CharField(blank=True, choices=[('%Y-%m-%d', '2025-01-15 (YYYY-MM-DD - ISO 8601)'), ('%d/%m/%Y', '15/01/2025 (DD/MM/YYYY)'), ('%m/%d/%Y', '01/15/2025 (MM/DD/YYYY)'), ('%d-%m-%Y', '15-01-2025 (DD-MM-YYYY)'), ('%m-%d-%Y', '01-15-2025 (MM-DD-YYYY)'), ('%Y/%m/%d', '2025/01/15 (YYYY/MM/DD)'), ('%d.%m.%Y', '15.01.2025 (DD.MM.YYYY)'), ('%Y%m%d', '20250115 (YYYYMMDD - compact)'), ('%d %b %Y', '15 Jan 2025 (DD Mon YYYY - abbreviated month)'), ('%d %B %Y', '15 January 2025 (DD Month YYYY - full month)'), ('%b %d, %Y', 'Jan 15, 2025 (Mon DD, YYYY)'), ('%B %d, %Y', 'January 15, 2025 (Month DD, YYYY)'), ('%d-%b-%Y', '15-Jan-2025 (DD-Mon-YYYY)'), ('%Y.%m.%d', '2025.01.15 (YYYY.MM.DD)'), ('%d/%m/%y', '15/01/25 (DD/MM/YY - 2-digit year)'), ('%m/%d/%y', '01/15/25 (MM/DD/YY - 2-digit year)'), ('%y-%m-%d', '25-01-15 (YY-MM-DD - 2-digit year)'), ('%y%m%d', '250115 (YYMMDD - compact 2-digit year)')], default='%Y-%m-%d', help_text='Select the format that matches your date column', max_length=255, verbose_name='Date Format'),
        ),
        migrations.AlterField(
            model_name='standardcsvconfig',
            name='datetime_format',
            field=models.CharField(blank=True, choices=[('%Y-%m-%d %H:%M:%S', '2025-01-15 14:30:45 (YYYY-MM-DD HH:MM:SS - ISO 8601)'), ('%Y-%m-%d %H:%M:%S.%f', '2025-01-15 14:30:45.123456 (with microseconds)'), ('%Y-%m-%dT%H:%M:%S', '2025-01-15T14:30:45 (ISO 8601 with T separator)'), ('%Y-%m-%dT%H:%M:%SZ', '2025-01-15T14:30:45Z (ISO 8601 UTC)'), ('%Y-%m-%d %H:%M', '2025-01-15 14:30 (YYYY-MM-DD HH:MM - no seconds)'), ('%d/%m/%Y %H:%M:%S', '15/01/2025 14:30:45 (DD/MM/YYYY HH:MM:SS)'), ('%d/%m/%Y %H:%M', '15/01/2025 14:30 (DD/MM/YYYY HH:MM - no seconds)'), ('%m/%d/%Y %H:%M:%S', '01/15/2025 14:30:45 (MM/DD/YYYY HH:MM:SS)'), ('%m/%d/%Y %H:%M', '01/15/2025 14:30 (MM/DD/YYYY HH:MM - no seconds)'), ('%d-%m-%Y %H:%M:%S', '15-01-2025 14:30:45 (DD-MM-YYYY HH:MM:SS)'), ('%m-%d-%Y %H:%M:%S', '01-15-2025 14:30:45 (MM-DD-YYYY HH:MM:SS)'), ('%Y%m%d%H%M%S', '20250115143045 (YYYYMMDDHHMMSS - compact)'), ('%Y%m%d %H%M%S', '20250115 143045 (YYYYMMDD HHMMSS - compact with space)'), ('%d.%m.%Y %H:%M:%S', '15.01.2025 14:30:45 (DD.MM.YYYY HH:MM:SS)'), ('%d.%m.%Y %H:%M', '15.01.2025 14:30 (DD.MM.YYYY HH:MM - no seconds)'), ('%Y/%m/%d %H:%M:%S', '2025/01/15 14:30:45 (YYYY/MM/DD HH:MM:SS)'), ('%d %b %Y %H:%M:%S', '15 Jan 2025 14:30:45 (DD Mon YYYY HH:MM:SS)'), ('%d %B %Y %H:%M:%S', '15 January 2025 14:30:45 (DD Month YYYY HH:MM:SS)'), ('%Y-%m-%d %I:%M:%S %p', '2025-01-15 02:30:45 PM (YYYY-MM-DD 12-hour with AM/PM)'), ('%m/%d/%Y %I:%M:%S %p', '01/15/2025 02:30:45 PM (MM/DD/YYYY 12-hour with AM/PM)'), ('%d/%m/%Y %I:%M:%S %p', '15/01/2025 02:30:45 PM (DD/MM/YYYY 12-hour with AM/PM)'), ('%a, %d %b %Y %H:%M:%S', 'Wed, 15 Jan 2025 14:30:45 (RFC 2822)')], default='%Y-%m-%d %H:%M:%S', help_text='Select the format that matches your datetime column', max_length=255, verbose_name='Datetime Format'),
        ),
        migrations.AlterField(
            model_name='standardcsvconfig',
            name='delimiter',
            field=models.CharField(choices=[(',', 'Comma (,)'), ('\t', 'Tab (\\t)'), (';', 'Semicolon (;)'), ('|', 'Pipe (|)'), (' ', 'Space ( )'), (':', 'Colon (:)')], default=',', help_text='Character used to separate values', max_length=5, verbose_name='CSV Delimiter'),
        ),
        migrations.AlterField(
            model_name='standardcsvconfig',
            name='time_format',
            field=models.CharField(blank=True, choices=[('%H:%M:%S', '14:30:45 (HH:MM:SS - 24-hour with seconds)'), ('%H:%M', '14:30 (HH:MM - 24-hour without seconds)'), ('%H:%M:%S.%f', '14:30:45.123456 (HH:MM:SS.microseconds)'), ('%I:%M:%S %p', '02:30:45 PM (12-hour with AM/PM and seconds)'), ('%I:%M %p', '02:30 PM (12-hour with AM/PM, no seconds)'), ('%H%M%S', '143045 (HHMMSS - compact 24-hour)'), ('%H%M', '1430 (HHMM - compact 24-hour, no seconds)'), ('%I:%M:%S%p', '02:30:45PM (12-hour, no space before AM/PM)'), ('%I:%M%p', '02:30PM (12-hour, no seconds, no space)'), ('%H.%M.%S', '14.30.45 (HH.MM.SS - dot separator)'), ('%H.%M', '14.30 (HH.MM - dot separator, no seconds)')], default='%H:%M:%S', help_text='Select the format that matches your time column', max_length=255, verbose_name='Time Format'),
        ),
    ]
