# Generated by Django 5.1.9 on 2025-10-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0019_alter_standardcsvconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardcsvconfig',
            name='datetime_format',
            field=models.CharField(blank=True, choices=[('%Y-%m-%d %H:%M:%S', '2025-01-15 14:30:45 (YYYY-MM-DD HH:MM:SS - ISO 8601)'), ('%Y-%m-%d %H:%M:%S.%f', '2025-01-15 14:30:45.123456 (with microseconds)'), ('%Y-%m-%dT%H:%M:%S', '2025-01-15T14:30:45 (ISO 8601 with T separator)'), ('%Y-%m-%dT%H:%M:%SZ', '2025-01-15T14:30:45Z (ISO 8601 UTC)'), ('%Y-%m-%d %H:%M', '2025-01-15 14:30 (YYYY-MM-DD HH:MM - no seconds)'), ('%d/%m/%Y %H:%M:%S', '15/01/2025 14:30:45 (DD/MM/YYYY HH:MM:SS)'), ('%d/%m/%Y %H:%M', '15/01/2025 14:30 (DD/MM/YYYY HH:MM - no seconds)'), ('%m/%d/%Y %H:%M:%S', '01/15/2025 14:30:45 (MM/DD/YYYY HH:MM:SS)'), ('%m/%d/%Y %H:%M', '01/15/2025 14:30 (MM/DD/YYYY HH:MM - no seconds)'), ('%d-%m-%Y %H:%M:%S', '15-01-2025 14:30:45 (DD-MM-YYYY HH:MM:SS)'), ('%m-%d-%Y %H:%M:%S', '01-15-2025 14:30:45 (MM-DD-YYYY HH:MM:SS)'), ('%Y%m%d%H%M%S', '20250115143045 (YYYYMMDDHHMMSS - compact)'), ('%Y%m%d%H%M', '202501151430 (YYYYMMDDHHMM - compact no seconds)'), ('%Y%m%d %H%M%S', '20250115 143045 (YYYYMMDD HHMMSS - compact with space)'), ('%Y%m%d %H%M', '20250115 1430 (YYYYMMDD HHMM - compact no seconds with space)'), ('%d.%m.%Y %H:%M:%S', '15.01.2025 14:30:45 (DD.MM.YYYY HH:MM:SS)'), ('%d.%m.%Y %H:%M', '15.01.2025 14:30 (DD.MM.YYYY HH:MM - no seconds)'), ('%Y/%m/%d %H:%M:%S', '2025/01/15 14:30:45 (YYYY/MM/DD HH:MM:SS)'), ('%d %b %Y %H:%M:%S', '15 Jan 2025 14:30:45 (DD Mon YYYY HH:MM:SS)'), ('%d %B %Y %H:%M:%S', '15 January 2025 14:30:45 (DD Month YYYY HH:MM:SS)'), ('%Y-%m-%d %I:%M:%S %p', '2025-01-15 02:30:45 PM (YYYY-MM-DD 12-hour with AM/PM)'), ('%m/%d/%Y %I:%M:%S %p', '01/15/2025 02:30:45 PM (MM/DD/YYYY 12-hour with AM/PM)'), ('%d/%m/%Y %I:%M:%S %p', '15/01/2025 02:30:45 PM (DD/MM/YYYY 12-hour with AM/PM)'), ('%a, %d %b %Y %H:%M:%S', 'Wed, 15 Jan 2025 14:30:45 (RFC 2822)')], default='%Y-%m-%d %H:%M:%S', help_text='Select the format that matches your datetime column', max_length=255, verbose_name='Datetime Format'),
        ),
    ]
