# Generated by Django 5.1.9 on 2025-10-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0020_alter_standardcsvconfig_datetime_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpstationlink',
            name='filename_date_format',
            field=models.CharField(blank=True, choices=[('YYYYMMDD', 'YYYYMMDD - e.g., 20250115'), ('YYYY-MM-DD', 'YYYY-MM-DD - e.g., 2025-01-15'), ('YYYY_MM_DD', 'YYYY_MM_DD - e.g., 2025_01_15'), ('YYMMDD', 'YYMMDD - e.g., 250115'), ('DDMMYYYY', 'DDMMYYYY - e.g., 15012025'), ('MMDDYYYY', 'MMDDYYYY - e.g., 01152025'), ('DD-MM-YYYY', 'DD-MM-YYYY - e.g., 15-01-2025'), ('MM-DD-YYYY', 'MM-DD-YYYY - e.g., 01-15-2025'), ('YYYYMMDDHH', 'YYYYMMDDHH - e.g., 2025011514'), ('YYYYMMDDHHMMSS', 'YYYYMMDDHHMMSS - e.g., 20250115143045'), ('YYYY-MM-DD_HH', 'YYYY-MM-DD_HH - e.g., 2025-01-15_14'), ('YYYY-MM-DD_HHMMSS', 'YYYY-MM-DD_HHMMSS - e.g., 2025-01-15_143045')], help_text='Format of the date in the filename (appears before file extension)', max_length=50, null=True, verbose_name='Filename Date Format'),
        ),
        migrations.AddField(
            model_name='ftpstationlink',
            name='filter_files_by_date',
            field=models.BooleanField(default=False, help_text='Check if filenames contain dates that should be used to filter which files to download', verbose_name='Filter files by date in filename'),
        ),
    ]
