# Generated by Django 5.1.9 on 2025-10-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0022_alter_ftpstationlink_filename_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardcsvconfig',
            name='has_header',
            field=models.BooleanField(default=True, help_text='Check if the first row (after skipped rows) contains column names. If unchecked, columns will be named as column_1, column_2, etc.', verbose_name='File has header row'),
        ),
    ]
