# Generated by Django 5.1.9 on 2025-11-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0023_standardcsvconfig_has_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmetftpupload',
            name='stations_csv_ftp_path',
            field=models.CharField(blank=True, help_text='Path on the FTP/SFTP server to upload the stations metadata CSV file', max_length=255, null=True, verbose_name='Stations Metadata CSV FTP Path'),
        ),
        migrations.AddField(
            model_name='smartmetftpupload',
            name='stations_file_name',
            field=models.CharField(blank=True, default='stations.csv', help_text='Name of the stations metadata CSV file to upload', max_length=255, null=True, verbose_name='Stations Metadata CSV File Name'),
        ),
    ]
