# Generated by Django 5.1.9 on 2025-11-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0024_smartmetftpupload_stations_csv_ftp_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmetftpupload',
            name='update_stations_metadata_after_station_update',
            field=models.BooleanField(default=True, help_text='If checked, the stations metadata CSV file will be uploaded to the FTP/SFTP server on saving this configuration', verbose_name='Update stations metadata on save'),
        ),
    ]
