# Generated by Django 5.1.9 on 2026-01-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0025_smartmetftpupload_update_stations_metadata_after_station_update'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ftpstationdatafile',
            index=models.Index(fields=['station_link', 'file_name', 'id'], name='idx_ftpfile_station_file_id'),
        ),
    ]
