# Generated by Django 5.1.9 on 2026-02-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0026_ftpstationdatafile_idx_ftpfile_station_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpstationdatafile',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
