# Generated by Django 5.1.9 on 2026-02-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0027_ftpstationdatafile_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpstationlink',
            name='filename_date_format',
            field=models.CharField(blank=True, choices=[('YYYYMMDD', 'YYYYMMDD - e.g., 20250115'), ('YYYYMMDDHH', 'YYYYMMDDHH - e.g., 2025011514'), ('YYYYMMDDHHMM', 'YYYYMMDDHHMM - e.g., 202501151430'), ('YYYYMMDDHHMMSS', 'YYYYMMDDHHMMSS - e.g., 20250115143045'), ('YYMMDD', 'YYMMDD - e.g., 250115'), ('YYMMDDHHMM', 'YYMMDDHHMM - e.g., 2501151430'), ('DDMMYYYY', 'DDMMYYYY - e.g., 15012025'), ('MMDDYYYY', 'MMDDYYYY - e.g., 01152025'), ('DDMMYY', 'DDMMYY - e.g., 150125'), ('MMDDYY', 'MMDDYY - e.g., 011525'), ('YYYYMMDD_HHMMSS', 'YYYYMMDD_HHMMSS - e.g., 20250115_143045'), ('YYYY-MM-DD', 'YYYY-MM-DD - e.g., 2025-01-15'), ('YYYY-MM-DD-HH', 'YYYY-MM-DD-HH - e.g., 2025-01-15-14'), ('YYYY-MM-DD-HHMM', 'YYYY-MM-DD-HHMM - e.g., 2025-01-15-1430'), ('YYYY-MM-DD-HHMMSS', 'YYYY-MM-DD-HHMMSS - e.g., 2025-01-15-143045'), ('DD-MM-YYYY', 'DD-MM-YYYY - e.g., 15-01-2025'), ('MM-DD-YYYY', 'MM-DD-YYYY - e.g., 01-15-2025'), ('YY-MM-DD', 'YY-MM-DD - e.g., 25-01-15'), ('YYYY_MM_DD', 'YYYY_MM_DD - e.g., 2025_01_15'), ('YYYY_MM_DD_HH', 'YYYY_MM_DD_HH - e.g., 2025_01_15_14'), ('YYYY_MM_DD_HHMM', 'YYYY_MM_DD_HHMM - e.g., 2025_01_15_1430'), ('YYYY_MM_DD_HHMMSS', 'YYYY_MM_DD_HHMMSS - e.g., 2025_01_15_143045'), ('DD_MM_YYYY', 'DD_MM_YYYY - e.g., 15_01_2025'), ('MM_DD_YYYY', 'MM_DD_YYYY - e.g., 01_15_2025'), ('YYYY.MM.DD', 'YYYY.MM.DD - e.g., 2025.01.15'), ('DD.MM.YYYY', 'DD.MM.YYYY - e.g., 15.01.2025'), ('MM.DD.YYYY', 'MM.DD.YYYY - e.g., 01.15.2025'), ('YYYY-MM-DDTHH', 'YYYY-MM-DDTHH - e.g., 2025-01-15T14'), ('YYYY-MM-DDTHHMMSS', 'YYYY-MM-DDTHHMMSS - e.g., 2025-01-15T143045'), ('YYYY-MM-DDTHH:MM:SS', 'YYYY-MM-DDTHH:MM:SS - e.g., 2025-01-15T14:30:45'), ('YYYYDDD', 'YYYYDDD - e.g., 2025015 (Julian day)'), ('YYDDD', 'YYDDD - e.g., 25015 (Julian day)'), ('YYYYMM', 'YYYYMM - e.g., 202501'), ('YYYY-MM', 'YYYY-MM - e.g., 2025-01'), ('YYYY_MM', 'YYYY_MM - e.g., 2025_01'), ('YYYY-MMM-DD', 'YYYY-MMM-DD - e.g., 2025-Jan-15'), ('DD-MMM-YYYY', 'DD-MMM-YYYY - e.g., 15-Jan-2025'), ('YYYYMMMDD', 'YYYYMMMDD - e.g., 2025Jan15'), ('DDMMMYYYY', 'DDMMMYYYY - e.g., 15Jan2025'), ('TIMESTAMP', 'Unix Timestamp - e.g., 1705329600')], help_text='Format of the date in the filename (appears before file extension)', max_length=50, null=True, verbose_name='Filename Date Format'),
        ),
    ]
