# Generated by Django 5.1.9 on 2026-02-04 13:28

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0028_alter_ftpstationlink_filename_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpstationlink',
            name='filename_date_timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone to use when parsing dates from filenames', verbose_name='Filename Date Timezone'),
        ),
    ]
