# Generated by Django 5.1.9 on 2026-02-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_ftp_plugin', '0030_remove_ftpstationlink_filter_files_by_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardcsvconfig',
            name='no_data_value',
            field=models.FloatField(blank=True, help_text='Value used in the data, to indicate a missing observation', null=True, verbose_name='No Data Value'),
        ),
    ]
